---
- include_vars: groups.yml

- name: Create groups
  sudo: yes
  group: name={{ item.name }} gid={{ item.gid }}
  #"groups" is a reserved word, so using grps
  with_items: grps

- name: Give sudo privilege to ops group
  sudo: yes
  copy: src=swire_sudoers dest=/etc/sudoers.d/swire_sudoers backup=yes owner=root group=root mode=0440
         validate='visudo -cf %s'
